### ISSUE TITLE
Compatibility with the latest tokenizers package

### ISSUE THREAD

**Issue by function2-llx** [Lightning-AI/metrics#1276] opened 2022-10-17 20:54 UTC
## 🚀 Feature

It would be nice if torchmetrics would be compatible with the lastest tokenizers package. Currently, with the latest torchmetrics (0.10.0) and tokenizers (0.13.1) installed, I've got following error traceback (some information are omitted):

```
  File ".../pytorch_lightning/callbacks/callback.py", line 25, in <module>
    from pytorch_lightning.utilities.types import STEP_OUTPUT
......
  File ".../torchmetrics/functional/text/helper_embedding_metric.py", line 26, in <module>
    from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
......
  File ".../transformers/utils/versions.py", line 49, in _compare_versions
    raise ImportError(
ImportError: tokenizers>=0.11.1,!=0.11.3,<0.13 is required for a normal functioning of this module, but found tokenizers==0.13.1.
Try: pip install transformers -U or pip install -e '.[dev]' if you're working with git main
```

**Comment by stancld** [comment] 2022-10-17 22:03
Hi @function2-llx, thanks for reporting this issue. Could you please provide us with a reproducible piece of code? I use package version you mention and try to do thet import and everything works fine to me 🤔

**Comment by SkafteNicki** [comment] 2022-10-24 14:32
I also just tried and everything seems to be in order when I try to import
```python
from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase
```
on `v0.10.0` or master of torchmetrics.

**Comment by SkafteNicki** [comment] 2022-10-31 13:29
Closing issue.

**Closed by SkafteNicki** 2022-10-31 13:29 UTC
Labels: enhancement, waiting on author

**Comment by function2-llx** [comment] 2022-11-08 05:35
Hello, 

I am sincerely sorry for my late reply. I'm not doing things well in recent weeks.

After a closer look, I think this issue is caused by the incompatibility between https://github.com/huggingface/transformers and https://github.com/huggingface/tokenizers. I should have upgraded the `transformers` first or submitted an issue in either of the huggingface's repository. Now I've upgraded the `transformer` package, and the issue has disappeared. 

Once again, I'm so sorry for wasting your time. I'm really enjoying your work (including pytorch-lightning), hope I can do better when trying to help in the future.
