### ISSUE TITLE
torchmetric freezes the training

### ISSUE THREAD

**Issue by thistlillo** [Lightning-AI/metrics#1152] opened 2022-07-19 15:49 UTC
When I use `torchmetrics` in my pytorch code, training gets stuck in waiting for a process.

Please consider this code:

```
metrics_avg = ["micro", "macro", "weighted"]
self.metrics = [Accuracy(average=t, num_classes=n_classes) for t in metrics_avg]
self.metrics_avg = metrics_avg
[...]
print("resetting metrics")
for m in self.metrics:
      m.reset()
 print("done")

# epoch
for bi, (images, labels, text) in enumerate(dl):
       if bi == 0:
           print("IMAGES:", images.shape)
           print("LABELS:", labels.shape)
           print("TEXT:", text.shape)

       _, _, semantic_features = self.cnn(images)

      [...]
      # > 1
      for m in self.metrics:
            m(semantic_features, labels.long())
      # < 1
[...]
```
The training very often, but not always, gets stuck and only the information on the batch are printed. If I interrupt the process while nothing is happening, I get this error message:
```
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/opt/conda/envs/torch/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
```
As soon as I remove the code for the metrics (indicated with `#>1` and `#<1`) everything goes back to normal.
What am I doing wrong?

Using:
```
  - pytorch
  - pytorch=1.11.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - torchaudio=0.11.0=py38_cu113
  - torchmetrics=0.8.2=pyhd8ed1ab_0
  - torchvision=0.12.0=py38_cu113

```

**Comment by SkafteNicki** [comment] 2022-07-20 09:18
Hi @thistlillo,
Could you please provide what the shape of `semantic_features` and `labels` are in the case when the code gets stuck?
This can probably help me figure out what is happening.

**Comment by thistlillo** [comment] 2022-07-20 13:41
Sorry @SkafteNicki I would have replied later. I am still fighting against that freezing: it is the pytorch dataloder that gets stuck waiting for some process to end, torchmetrics had no fault. It does not happen 100% of the times and sometimes it does not freeze for several trainings: it happened to NOT have frozen when I removed torchmetrics, but then it started again after a while.

**Comment by SkafteNicki** [comment] 2022-07-21 08:41
Alright, then I will close this issue as it seems the problem is unrelated to torchmetrics

**Closed by SkafteNicki** 2022-07-21 08:41 UTC
Labels: bug / fix, help wanted
