### ISSUE TITLE
I can't get rid of the userwarning of WER and CER: `Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has not been set for this class...`

### ISSUE THREAD

**Issue by Xiaotian0726** [Lightning-AI/metrics#1359] opened 2022-11-24 06:49 UTC
I can't get rid of this userwarning while using `WordErrorRate` and `CharErrorRate`: 
```shell
/home/hxt/ASR_adversarial_examples/venv/lib/python3.7/site-packages/torchmetrics/utilities/prints.py:36: UserWarning: Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class (WordErrorRate). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
```

According to the description above, a relevant property called `full_state_update` should be set for WER but not.

Actually, my `torchmetrics` version is: 
```shell
torchmetrics                    0.9.3
```

and the `full_state_update` property has been set already according to source code:
```python
class WordErrorRate(Metric):
    is_differentiable: bool = False
    higher_is_better: bool = False
    full_state_update: bool = False
    
    # ...
```

Then I searched the source code for where this userwarning was thrown, and I found this in the base class `torchmetrics/Metrics`:
```python
class Metric(Module, ABC):

    # ...

    is_differentiable: Optional[bool] = None
    higher_is_better: Optional[bool] = None
    full_state_update: Optional[bool] = None

    def __init__(
        self,
        **kwargs: Any,
    ) -> None:
        super().__init__()

        # ...

        if self.full_state_update is None and not is_overridden("forward", self, Metric):
            rank_zero_warn(
                f"""Torchmetrics v0.9 introduced a new argument class property called `full_state_update` that has
                not been set for this class ({self.__class__.__name__}). The property determines if `update` by
                default needs access to the full metric state. If this is not the case, significant speedups can be
                achieved and we recommend setting this to `False`.
                We provide an checking function
                `from torchmetrics.utilities import check_forward_full_state_property`
                that can be used to check if the `full_state_update=True` (old and potential slower behaviour,
                default for now) or if `full_state_update=False` can be used safely.
                """,
                UserWarning,
            )
```

So is this a problem about class member `full_state_update` overriding?

**Comment by Xiaotian0726** [comment] 2022-11-24 06:53
And how to get rid of this? Thank you.

**Comment by SkafteNicki** [comment] 2022-11-24 07:38
Hi @Xiaotian0726, thanks for reporting this issue.
I am a bit confused that you still get the warning even when you overwrite the property in your metric class. Here you can see that we do exactly that for our own metrics:
https://github.com/Lightning-AI/metrics/blob/ed2249d1e250dbfc4f2e654b455f43f3d29abfb1/src/torchmetrics/regression/mse.py#L42-L44
Also I cannot reproduce the error on v0.9.3 with this small example:
```python
from torchmetrics import Metric

class WordErrorRate(Metric):
    full_state_update: bool = False

    def update(self):
        pass

    def compute(self):
        return 1

if __name__ == "__main__":
    metric = WordErrorRate()
```
you have not setup your warnings filtering in some weird way?

Regardless of all this the warning has been removed from the next release in this PR https://github.com/Lightning-AI/metrics/pull/1349. You can update directly from master now if you want the change:
```
pip install git+https://github.com/Lightning-AI/metrics.git
```
or wait for the next release (it will probably be within a week or so).

**Comment by SkafteNicki** [comment] 2022-11-24 08:33
Yes, the warning is first removed it what will be v0.11.0, which will officially be released within the next week.
Closing issue.

**Closed by SkafteNicki** 2022-11-24 08:33 UTC
Labels: bug / fix, help wanted
