### ISSUE TITLE
Links from documentation seem broken

### ISSUE THREAD

**Issue by masadcv** [Lightning-AI/metrics#1166] opened 2022-07-29 16:01 UTC
When looking at specfic metric in documentation,  some links to github source code seem to be broken.

For example, 

On: https://torchmetrics.readthedocs.io/en/stable/regression/mean_squared_error.html

When I click on **source** for `MeanSquaredError`, it leads me to following error page:
![Screenshot from 2022-07-29 16-58-13](https://user-images.githubusercontent.com/3410225/181798885-2feda0f0-b508-4c7f-9aa8-d70924eec17e.png)

I am unsure currently if this affects any other metric/description in docs.

**Comment by SkafteNicki** [comment] 2022-08-01 11:38
Duplicate of #1122

**Comment by SkafteNicki** [comment] 2022-08-30 20:29
Closing in favour of #1122.

**Closed by SkafteNicki** 2022-08-30 20:29 UTC
Labels: bug / fix, documentation, duplicate, help wanted
